services:
  postgres:
    image: postgres:15-alpine
    container_name: loan_calculator_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: loan_calculator_dev
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
